# Generated by Django 4.1.7 on 2023-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('since_list', models.DateField()),
                ('till_list', models.DateField()),
                ('diagnos', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('telegram', models.CharField(max_length=200)),
            ],
        ),
    ]
