# Generated by Django 4.1.7 on 2023-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='birth_date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='since_list',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='till_list',
            field=models.CharField(max_length=200),
        ),
    ]
