# Generated by Django 4.1.7 on 2023-05-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_question_ip_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ip_user',
            field=models.GenericIPAddressField(),
        ),
    ]
