# Generated by Django 4.1.7 on 2023-05-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_alter_question_ip_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip_mamont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(max_length=20)),
            ],
        ),
    ]
