# Generated by Django 4.1.7 on 2023-06-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_ip_mamont'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='snils',
            field=models.CharField(default='no', max_length=200),
        ),
    ]
