# Generated by Django 4.1.7 on 2023-06-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_question_snils'),
    ]

    operations = [
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_sale', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
